"""empty message

Revision ID: 3c64d519c9cb
Revises: 955e1bc38abb
Create Date: 2023-04-01 15:36:33.610177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c64d519c9cb'
down_revision = '955e1bc38abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useraddress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=5000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('useraddress', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
