"""empty message

Revision ID: 53bc1531e512
Revises: 95f206f0f97d
Create Date: 2023-04-04 11:53:17.424156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53bc1531e512'
down_revision = '95f206f0f97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productstock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_wholesaleprice', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_wholesaleofferprice', sa.String(length=100), nullable=True))

    with op.batch_alter_table('productunit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wholesale_unit_name_en', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('wholesale_unit_name_ar', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wholesale_unit_desc_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wholesale_unit_desc_ar', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wholesale_unit_short_form_en', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('wholesale_unit_short_form_ar', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productunit', schema=None) as batch_op:
        batch_op.drop_column('wholesale_unit_short_form_ar')
        batch_op.drop_column('wholesale_unit_short_form_en')
        batch_op.drop_column('wholesale_unit_desc_ar')
        batch_op.drop_column('wholesale_unit_desc_en')
        batch_op.drop_column('wholesale_unit_name_ar')
        batch_op.drop_column('wholesale_unit_name_en')

    with op.batch_alter_table('productstock', schema=None) as batch_op:
        batch_op.drop_column('product_wholesaleofferprice')
        batch_op.drop_column('product_wholesaleprice')

    # ### end Alembic commands ###
