"""empty message

Revision ID: 60f5d18bef28
Revises: 5bdb29fea440
Create Date: 2023-04-08 09:59:59.827177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f5d18bef28'
down_revision = '5bdb29fea440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('active_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('active_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
