"""empty message

Revision ID: 955e1bc38abb
Revises: 3d6d42570480
Create Date: 2023-04-01 14:24:56.417091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955e1bc38abb'
down_revision = '3d6d42570480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
