"""empty message

Revision ID: b7879c85114e
Revises: 60f5d18bef28
Create Date: 2023-04-08 10:04:13.723050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7879c85114e'
down_revision = '60f5d18bef28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('active_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('active_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
