"""empty message

Revision ID: c664fdce0132
Revises: a1fe586b7c98
Create Date: 2023-04-08 13:43:20.248715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c664fdce0132'
down_revision = 'a1fe586b7c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_coupons', schema=None) as batch_op:
        batch_op.drop_column('used_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
