"""empty message

Revision ID: ff067d6af8a4
Revises: b7879c85114e
Create Date: 2023-04-08 11:16:04.457297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff067d6af8a4'
down_revision = 'b7879c85114e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('active_status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('active_status',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
